[package]
name = "piper-synth"
version = "0.1.0"
edition = "2021"

[dependencies]
sonic-sys = { path = "../sonic-sys" }
piper-model = { path = "../piper-model" }
rayon = "1.7.0"
crossbeam-channel = "0.5.8"
once_cell = "1.17.1"
